name: Verify Formulas

on: pull_request

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: brew tap
        run: brew tap leancodepl/tools

      - name: brew install --build-from-source ./Formula/mobile-tools.rb
        run: brew install mobile-tools

      - name: brew audit
        run: brew audit mobile-tools --strict --online

      - name: brew test
        run: brew test mobile-tools
