name: Verify Formulas

on: pull_request

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: brew tap
        run: brew tap leancodepl/tools

      - name: brew install
        run: cat ./Formula/mobile-tools.rb && brew install ./Formula/mobile-tools.rb

      - name: brew audit
        run: brew audit mobile-tools --strict --online

      - name: brew test
        run: brew test mobile-tools
